<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="HtmlSanitizer" Version="9.2.995" />
    <PackageReference Include="Mapster" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\HospitalSaoJose.Communication\HospitalSaoJose.Communication.csproj" />
    <ProjectReference Include="..\..\Shared\HospitalSaoJose.Exception\HospitalSaoJose.Exception.csproj" />
    <ProjectReference Include="..\HospitalSaoJose.Domain\HospitalSaoJose.Domain.csproj" />
  </ItemGroup>

</Project>
